version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-prueba
    environment:
      POSTGRES_DB: microservicio-prueba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1995
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app-prueba
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservicio-prueba
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1995
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  pgdata:
